### PR TITLE
Add support for controlling close timeout

### PR DESCRIPTION
**Pull request by rounakdatta**
Hello Linus,
I'm proposing the capability to support https://github.com/thesephist/clozoom/issues/5. Thanks for this super-useful extension.

Screenshot of the updated popup:

image

### CODE REVIEW

**Comment by thesephist** [comment]
Hey @rounakdatta, thanks for the PR! On a first scan this looks pretty good, but I don't have bandwidth at the moment to test (before merging) and push out an update to the Chrome Web Store. I'll do so when I get a chance.

**Comment by rounakdatta** [comment]
Thanks @thesephist :) please take your time to review it!

**Comment by rounakdatta** [comment]
@thesephist in case you got a chance to to review this, please let me know! My friends/colleagues are loving this extension and would love to have this customized timer feature without having to load from source :)

**Comment by thesephist** [comment]
@rounakdatta Looks good to me! While I'm in the codebase again, I'm going to also update it to use Extension Manifest V3 and submit to the store. I'll post an update here when it's in review.

**Comment by thesephist** [comment]
In review! Apologizes for the long time gap to get this out.

Screen Shot 2022-08-02 at 21 56 31

**Comment by rounakdatta** [comment]
Thank you Linus, no worries :)
Love the creativity in all your self-projects!

**Pull request merged**
